import assert from 'node:assert/strict';
import test from 'node:test';
import {createTrainingDraft,exerciseFromLibrary} from '../src/lib/training.ts';
import {makeSession,sessionErrors,detailedVolume,progressionSuggestion,duplicateTraining,sessionDate,performanceSummary} from '../src/lib/training-tracking.ts';
import type {TrainingProgram} from '../src/types/index.ts';
function fixture():TrainingProgram{const p={...createTrainingDraft(1,'Test','2026-12-28'),id:1,created_at:'',updated_at:''};p.days[0].exercises.push(exerciseFromLibrary({id:'press',name:'Press',muscle_group:'Pectoral'},5));return p;}
test('session keeps prescription independent and rejects incomplete completion',()=>{const p=fixture();const s=makeSession(p,p.days[0].id,1);s.exercises[0].target.sets=8;assert.equal(p.days[0].exercises[0].prescriptions[0].sets,3);s.completed=true;assert.ok(sessionErrors(s).length);s.exercises[0].sets.forEach(v=>v.completed=true);assert.deepEqual(sessionErrors(s),[]);s.exercises[0].sets[0].kg=-10;assert.ok(sessionErrors(s).length);});
test('indirect volume uses explicit muscles and configurable weight',()=>{const p=fixture();p.days[0].exercises[0].secondary_muscles=['Tríceps'];p.days[0].exercises[0].indirect_factor=.5;const volume=detailedVolume(p,1);assert.equal(volume.find(v=>v.muscle==='Pectoral')?.direct,3);assert.equal(volume.find(v=>v.muscle==='Tríceps')?.indirect,1.5);});
test('progression requires completed history and stops on high fatigue',()=>{const p=fixture();const ex=p.days[0].exercises[0];const s=makeSession(p,p.days[0].id,1);assert.equal(progressionSuggestion(ex,[s],2).action,'hold');s.completed=true;s.exercises[0].sets.forEach(v=>{v.kg=40;v.reps=12;v.rir=2;v.completed=true;});const next={...structuredClone(s),date:'2026-09-20'};assert.equal(progressionSuggestion(ex,[s,next],2).load_kg,41);s.fatigue=9;assert.equal(progressionSuggestion(ex,[s,next],2).action,'review');assert.equal(performanceSummary([s])[0].tonnage,1440);});
test('template duplication changes identities and removes client feedback',()=>{const p=fixture();const copy=duplicateTraining(p,2);assert.equal(copy.client_id,2);assert.equal(copy.status,'draft');assert.notEqual(copy.days[0].id,p.days[0].id);assert.notEqual(copy.days[0].exercises[0].id,p.days[0].exercises[0].id);copy.days[0].exercises[0].prescriptions[0].sets=9;assert.equal(p.days[0].exercises[0].prescriptions[0].sets,3);assert.equal(copy.review,undefined);});
test('agenda respects configured rest gaps and crosses year boundaries',()=>{const p=fixture();p.days[0].weekday_offset=4;assert.equal(sessionDate(p,0,1),'2027-01-01');assert.equal(sessionDate(p,0,2),'2027-01-08');});
