'use client';
import {useEffect,useState,useCallback} from 'react';
import {supabase} from '@/lib/supabase';
import {db,retryCloudSave} from '@/lib/db';
import {readPortal,grantPortal,memberships,writeActivity,type PortalData} from '@/lib/client-portal';
import {SessionTracker} from './SessionTracker';
import {CareAgenda} from './CareAgenda';
import {trainingDateValue} from '@/lib/training';
import {foodRatio} from '@/lib/meal-day';
export function ClientCare({clientId,owner:providedOwner,coach=false,initialTab='training',showAccess=true,agendaOnly=false}:{clientId:number;owner?:string;coach?:boolean;initialTab?:string;showAccess?:boolean;agendaOnly?:boolean}){
 const [owner,setOwner]=useState(providedOwner??'');const [data,setData]=useState<PortalData|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [email,setEmail]=useState(coach?db.getClient(clientId)?.email??'':'');const [enabled,setEnabled]=useState(false);const [tab,setTab]=useState(initialTab);const [weight,setWeight]=useState('');const [notes,setNotes]=useState('');const [date,setDate]=useState(trainingDateValue());
 const fetchData=useCallback(async()=>{const id=providedOwner??(await supabase.auth.getUser()).data.user?.id;if(!id)throw new Error('Inicia sesión.');const result=await readPortal(id,clientId);if(coach)result.trainingPrograms=db.getTrainingPrograms(clientId);const entry=coach?(await memberships()).find(m=>m.owner_id===id&&m.client_id===clientId):undefined;return {id,result,entry};},[providedOwner,clientId,coach]);
 const applyData=useCallback(({id,result,entry}:Awaited<ReturnType<typeof fetchData>>)=>{setOwner(id);setData(result);if(coach){setEnabled(entry?.enabled??false);if(entry)setEmail(entry.email);}},[coach]);
 async function load(){try{applyData(await fetchData());}catch(e){setMessage((e as Error).message);}}
 useEffect(()=>{let live=true;void fetchData().then(value=>{if(live)applyData(value);}).catch(e=>{if(live)setMessage(e.message);});return ()=>{live=false;};},[fetchData,applyData]);
 async function access(enable:boolean){setBusy(true);try{await retryCloudSave();await grantPortal(clientId,email,enable);setEnabled(enable);setMessage(enable?'Acceso habilitado. Comparte el enlace del portal con el cliente.':'Acceso revocado.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function checkin(){if(!Number.isFinite(Number(weight))||Number(weight)<=0)return;setBusy(true);try{await writeActivity(owner,clientId,{id:crypto.randomUUID(),kind:'checkin',data:{date,weight:Number(weight),notes}});setMessage('Check-in enviado al coach.');setNotes('');await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function meal(plan:number,mealTime:string,rest:boolean,complete:boolean){setBusy(true);try{const existing=data?.activity.find(a=>a.kind==='meal'&&a.data.plan_id===plan&&a.data.meal_time===mealTime&&a.data.date===date&&a.data.rest===rest);await writeActivity(owner,clientId,{id:existing?.id??crypto.randomUUID(),kind:'meal',data:{date,plan_id:plan,meal_time:mealTime,rest,completed:complete}});await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(agendaOnly)return <>{message&&<p role="status" className="care-notice">{message}</p>}{data?<CareAgenda owner={owner} data={data} coach={coach} onSaved={()=>void load()}/>:<section className="care-card agenda-empty"><strong>Cargando agenda…</strong><p>Estamos reuniendo las fechas de este cliente.</p></section>}</>;
 return <div className="care-page"><header className="care-card care-heading"><div><span className="training-kicker">{coach?'SEGUIMIENTO DEL CLIENTE':'MI ESPACIO'}</span><h1>{data?.client.name??'Cargando expediente…'}</h1><p>Dieta, entrenamiento y progreso en un solo lugar.</p></div><button disabled={busy} onClick={()=>void load()}>Actualizar</button></header>
 {coach&&showAccess&&<section className="care-card"><h2>Acceso del cliente</h2><p>{enabled?'Habilitado':'Sin acceso activo'} · Este paso es independiente de la Agenda.</p><ol className="care-access-steps"><li><b>1</b><span>Confirma el correo y pulsa <strong>Habilitar acceso</strong>.</span></li><li><b>2</b><span>Copia y comparte el enlace del portal.</span></li><li><b>3</b><span>El cliente valida su correo una vez; después entra con contraseña.</span></li></ol><p>Ahí puede consultar dieta y entrenamiento y registrar su avance. Solo el coach modifica la planificación.</p><div className="care-form care-access-form"><label>Correo autorizado<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button disabled={busy||!email} onClick={()=>void access(true)}>Habilitar acceso</button><button disabled={busy||!enabled} onClick={()=>void access(false)}>Revocar acceso</button><a className="care-portal-link" href="/portal" target="_blank" rel="noopener noreferrer">Abrir portal</a><button onClick={()=>void navigator.clipboard.writeText(window.location.origin+'/portal').then(()=>setMessage('Enlace copiado.')).catch(()=>setMessage('Copia el enlace desde Abrir portal.'))}>Copiar enlace</button></div></section>}
 {message&&<p role="status" className="care-notice">{message}</p>}
 <nav className="care-tabs">{[['training','Entrenamiento'],['diet','Dieta'],['progress','Progreso'],['agenda','Agenda']].map(([key,label])=><button key={key} className={tab===key?'selected':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {data&&<>{tab==='training'&&<SessionTracker key={`${owner}-${clientId}`} owner={owner} clientId={clientId} programs={data.trainingPrograms} activity={data.activity} onSaved={()=>void load()}/>}
 {tab==='agenda'&&<CareAgenda owner={owner} data={data} coach={coach} onSaved={()=>void load()}/>}
 {tab==='diet'&&<section className="care-card"><h2>Mis planes de alimentación</h2><label>Fecha del registro<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{!data.mealPlans.length&&<p>No hay dietas asignadas.</p>}{data.mealPlans.map(plan=><details key={plan.id} className="care-inset"><summary>{plan.name} · {plan.total_kcal} kcal</summary>{(['normal','rest'] as const).map(type=>{const items=data.mealPlanItems.filter(i=>i.meal_plan_id===plan.id&&(i.day_type??'normal')===type);if(!items.length)return null;return <div key={type}><h3>{type==='rest'?'Rest Day':'Plan normal'}</h3>{[...new Set(items.map(i=>i.meal_time))].map(time=>{const done=data.activity.some(a=>a.kind==='meal'&&a.data.plan_id===plan.id&&a.data.meal_time===time&&a.data.date===date&&a.data.rest===(type==='rest')&&a.data.completed);return <article className="care-inset" key={time}><h4>{time.replace(/_/g,' ')}</h4>{items.filter(i=>i.meal_time===time).map(i=>{const food=data.foods.find(f=>f.id===i.food_id);return <p key={i.id}>{food?.name??'Alimento'} · {i.quantity} {i.serving_unit}{food?` · ${Math.round(food.kcal*foodRatio(i.quantity,i.serving_unit,food.serving_size))} kcal`:''}</p>;})}<button disabled={busy} onClick={()=>void meal(plan.id,time,type==='rest',!done)}>{done?'Completada ✓ · desmarcar':'Marcar comida completada'}</button></article>;})}</div>;})}</details>)}</section>}
 {tab==='progress'&&<section className="care-card"><h2>Check-ins y evolución</h2><div className="care-form"><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Peso (kg)<input type="number" min="1" max="500" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)}/></label><label>Notas del seguimiento<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button disabled={busy||!weight} onClick={()=>void checkin()}>Registrar check-in</button></div><div className="care-table-wrap"><table><thead><tr><th>Fecha</th><th>Peso</th><th>Notas</th></tr></thead><tbody>{data.activity.filter(a=>a.kind==='checkin').sort((a,b)=>String(b.data.date).localeCompare(String(a.data.date))).map(a=><tr key={a.id}><td>{String(a.data.date)}</td><td>{String(a.data.weight)} kg</td><td>{String(a.data.notes??'')}</td></tr>)}{data.measurements.map(m=><tr key={'m'+m.id}><td>{m.date.slice(0,10)}</td><td>{m.weight} kg</td><td>Evaluación del coach</td></tr>)}</tbody></table></div></section>}</>}
 </div>;
}
