'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {supabase} from '@/lib/supabase';
import {memberships,type PortalMembership} from '@/lib/client-portal';
import {ClientCare} from './ClientCare';
import {NumericInputNormalizer} from './NumericInputNormalizer';
import {authErrorMessage} from '@/lib/auth-errors';
export function ClientPortal(){
 const [user,setUser]=useState<string|null|undefined>(undefined);const [entries,setEntries]=useState<PortalMembership[]>([]);const [selected,setSelected]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [mode,setMode]=useState('login');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [dark,setDark]=useState(false);
 const identity=useRef<string|null|undefined>(undefined);
 useEffect(()=>{const {data}=supabase.auth.onAuthStateChange((_event,session)=>{const next=session?.user.id??null;if(identity.current!==next){identity.current=next;setEntries([]);setSelected('');setMessage('');setUser(next);}});return ()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!user)return;let live=true;void memberships().then(rows=>{if(live)setEntries(rows.filter(r=>r.enabled));}).catch(e=>{if(live)setMessage(e.message);});return ()=>{live=false;};},[user]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const result=mode==='signup'?await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+'/auth/callback?next=portal'}}):mode==='recovery'?await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/auth/callback?next=password&portal=1'}):await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(mode!=='login')setMessage('Revisa tu correo para continuar. El acceso al expediente requiere autorización de tu coach.');setPassword('');}catch(e){setMessage(authErrorMessage(e));}finally{setBusy(false);}}
 const entry=entries.find(e=>e.owner_id+':'+e.client_id===selected)??entries[0];
 return <div className={dark?'dark':''}><div className="care-portal"><NumericInputNormalizer/><header className="care-heading"><strong>DietForge · Portal del cliente</strong><div><button onClick={()=>setDark(!dark)}>{dark?'Modo claro':'Modo oscuro'}</button>{user&&<button onClick={()=>void supabase.auth.signOut()}>Cerrar sesión</button>}</div></header>
 {user===undefined?<p>Verificando sesión…</p>:!user?<section className="care-card care-login"><h1>{mode==='signup'?'Validar mi correo':mode==='recovery'?'Recuperar contraseña':'Iniciar sesión'}</h1><p>Usa el correo autorizado por tu coach.</p><form onSubmit={submit} className="care-stack"><label>Correo<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode!=='recovery'&&<label>Contraseña<input required minLength={mode==='signup'?12:1} maxLength={128} type="password" autoComplete={mode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button disabled={busy}>{busy?'Procesando…':mode==='signup'?'Crear cuenta y validar correo':mode==='recovery'?'Enviar recuperación':'Entrar'}</button></form><div className="care-list"><button onClick={()=>setMode(mode==='signup'?'login':'signup')}>{mode==='signup'?'Ya tengo cuenta':'Primera vez: validar correo'}</button><button onClick={()=>setMode(mode==='recovery'?'login':'recovery')}>{mode==='recovery'?'Volver al login':'Olvidé mi contraseña'}</button></div></section>:entry?<><label>Mi expediente<select value={entry.owner_id+':'+entry.client_id} onChange={e=>setSelected(e.target.value)}>{entries.map(e=><option key={e.owner_id+':'+e.client_id} value={e.owner_id+':'+e.client_id}>{e.name}</option>)}</select></label><ClientCare key={entry.owner_id+':'+entry.client_id} owner={entry.owner_id} clientId={entry.client_id}/></>:<section className="care-card"><h1>Tu sesión está lista</h1><p>Aún no hay un expediente autorizado para este correo. Tu coach puede habilitarlo desde Seguimiento y portal.</p><button onClick={()=>void memberships().then(setEntries).catch(e=>setMessage(e.message))}>Consultar acceso</button></section>}{message&&<p role="status">{message}</p>}</div></div>;
}
