'use client';
import {useEffect,useState,useCallback} from 'react';
import {supabase} from '@/lib/supabase';
import {db,retryCloudSave} from '@/lib/db';
import {readPortal,grantPortal,memberships,writeActivity,type PortalData} from '@/lib/client-portal';
import {SessionTracker} from './SessionTracker';
import {CareAgenda} from './CareAgenda';
import {trainingDateValue} from '@/lib/training';
import {useAutoRefresh} from '@/lib/use-auto-refresh';
import {PortalCheckIn} from './PortalCheckIn';
import {Bell,Check,X,Sun,Moon,Utensils} from 'lucide-react';
import {useDietNotice} from '@/lib/use-diet-notice';
import {foodRatio} from '@/lib/meal-day';
import {PortalMesocycle} from './PortalMesocycle';
const mealNames:Record<string,string>={pre_workout:'Pre-Entreno',intra_workout:'Intra-Entreno',post_workout:'Post-Entreno',meal1:'Comida 1',meal2:'Comida 2',meal3:'Comida 3',meal4:'Comida 4',meal5:'Comida 5',meal6:'Comida 6'};
export function ClientCare({clientId,owner:providedOwner,coach=false,initialTab='training',showAccess=true,agendaOnly=false,targetCheckIn}:{clientId:number;owner?:string;coach?:boolean;initialTab?:string;showAccess?:boolean;agendaOnly?:boolean;targetCheckIn?:string}){
 const [owner,setOwner]=useState(providedOwner??'');const [data,setData]=useState<PortalData|null>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [email,setEmail]=useState(coach?db.getClient(clientId)?.email??'':'');const [enabled,setEnabled]=useState(false);const [tab,setTab]=useState(initialTab);const [date,setDate]=useState(trainingDateValue());
 const fetchData=useCallback(async()=>{const id=providedOwner??(await supabase.auth.getUser()).data.user?.id;if(!id)throw new Error('Inicia sesión.');const result=await readPortal(id,clientId);if(coach)result.trainingPrograms=db.getTrainingPrograms(clientId);const entry=coach?(await memberships()).find(m=>m.owner_id===id&&m.client_id===clientId):undefined;return {id,result,entry};},[providedOwner,clientId,coach]);
 const applyData=useCallback(({id,result,entry}:Awaited<ReturnType<typeof fetchData>>)=>{setOwner(id);setData(result);if(coach){setEnabled(entry?.enabled??false);if(entry)setEmail(entry.email);}},[coach]);
 async function load(){try{applyData(await fetchData());}catch(e){setMessage((e as Error).message);}}
 useEffect(()=>{let live=true;void fetchData().then(value=>{if(live)applyData(value);}).catch(e=>{if(live)setMessage(e.message);});return ()=>{live=false;};},[fetchData,applyData]);
 const readLatest=useCallback(async()=>{const id=providedOwner??(await supabase.auth.getUser()).data.user?.id;if(!id)throw new Error('Inicia sesión.');return {id,result:await readPortal(id,clientId)};},[providedOwner,clientId]);
 const applyLatest=useCallback(({id,result}:Awaited<ReturnType<typeof readLatest>>)=>{setOwner(id);setData({...result,trainingPrograms:coach?db.getTrainingPrograms(clientId):result.trainingPrograms});},[coach,clientId]);
 const syncFailed=useAutoRefresh(readLatest,applyLatest);
 const dietNotice=useDietNotice(owner,clientId,!coach&&!agendaOnly);
 const markViewed=useCallback(async(id:string)=>{if(!coach)return;const {error}=await supabase.rpc('dietforge_notification_seen',{c:clientId,i:id});if(error){setMessage('Check-in abierto. No se pudo marcar la notificación como leída.');throw error;}},[coach,clientId]);
 async function access(enable:boolean){setBusy(true);try{await retryCloudSave();await grantPortal(clientId,email,enable);setEnabled(enable);setMessage(enable?'Acceso habilitado. Comparte el enlace del portal con el cliente.':'Acceso revocado.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function meal(plan:number,mealTime:string,rest:boolean,complete:boolean){setBusy(true);try{const existing=data?.activity.find(a=>a.kind==='meal'&&a.data.plan_id===plan&&a.data.meal_time===mealTime&&a.data.date===date&&a.data.rest===rest);await writeActivity(owner,clientId,{id:existing?.id??crypto.randomUUID(),kind:'meal',data:{date,plan_id:plan,meal_time:mealTime,rest,completed:complete}});await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(agendaOnly)return <>{message&&<p role="status" className="care-notice">{message}</p>}{data?<CareAgenda owner={owner} data={data} coach={coach} onSaved={()=>void load()}/>:<section className="care-card agenda-empty"><strong>Cargando agenda…</strong><p>Estamos reuniendo las fechas de este cliente.</p></section>}</>;
 return <div className="care-page"><header className="care-card care-heading"><div><span className="training-kicker">{coach?'SEGUIMIENTO DEL CLIENTE':'MI ESPACIO'}</span><h1>{data?.client.name??'Cargando expediente…'}</h1><p>Dieta, entrenamiento y progreso en un solo lugar.</p></div><p role="status">{syncFailed?"Sin conexión con el expediente · reintentando automáticamente":"Sincronización automática · cada 5 s"}</p></header>
 {coach&&showAccess&&<section className="care-card"><h2>Acceso del cliente</h2><p>{enabled?'Habilitado':'Sin acceso activo'} · Este paso es independiente de la Agenda.</p><ol className="care-access-steps"><li><b>1</b><span>Confirma el correo y pulsa <strong>Habilitar acceso</strong>.</span></li><li><b>2</b><span>Copia y comparte el enlace del portal.</span></li><li><b>3</b><span>El cliente valida su correo una vez; después entra con contraseña.</span></li></ol><p>Ahí puede consultar dieta y entrenamiento y registrar su avance. Solo el coach modifica la planificación.</p><div className="care-form care-access-form"><label>Correo autorizado<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button disabled={busy||!email} onClick={()=>void access(true)}>Habilitar acceso</button><button disabled={busy||!enabled} onClick={()=>void access(false)}>Revocar acceso</button><a className="care-portal-link" href="/portal" target="_blank" rel="noopener noreferrer">Abrir portal</a><button onClick={()=>void navigator.clipboard.writeText(window.location.origin+'/portal').then(()=>setMessage('Enlace copiado.')).catch(()=>setMessage('Copia el enlace desde Abrir portal.'))}>Copiar enlace</button></div></section>}
 {message&&<p role="status" className="care-notice">{message}</p>}
 <nav className="care-tabs" aria-label="Secciones del expediente">{[['training','Entrenamiento'],['diet','Comida'],['progress','Progreso'],['agenda','Agenda']].map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} className={tab===key?'selected':''} onClick={()=>setTab(key)}>{label}{key==='diet'&&dietNotice.pending&&<span className="care-tab-badge" aria-label="Ajuste de dieta sin leer"><Bell size={13}/><span>Nuevo</span></span>}</button>)}</nav>
 {data&&<>{<div className="care-tab-panel" hidden={tab!=='training'}>{!coach&&<PortalMesocycle programs={data.trainingPrograms}/>}<SessionTracker key={`${owner}-${clientId}`} owner={owner} clientId={clientId} programs={data.trainingPrograms} activity={data.activity} onSaved={()=>void load()} clientMode={!coach}/></div>}
 {tab==='agenda'&&<CareAgenda owner={owner} data={data} coach={coach} onSaved={()=>void load()}/>}
 {tab==='diet'&&<section className="care-card care-diet"><header><span className="training-kicker">TU ALIMENTACIÓN</span><h2>Mis planes de alimentación</h2></header>{dietNotice.pending&&<div className="care-diet-notice" role="status"><Bell size={20}/><div><strong>Tu coach hizo un ajuste en tu alimentación</strong><p>Revisa las comidas y cantidades actualizadas antes de continuar con tu plan.</p>{dietNotice.error&&<p role="alert">{dietNotice.error}</p>}</div><button aria-label="Cerrar aviso de ajuste" disabled={dietNotice.closing} onClick={()=>void dietNotice.close()}><X size={18}/></button></div>}{dietNotice.failed&&<p role="status">No pudimos consultar los avisos de ajustes. Reintentando automáticamente.</p>}<label>Fecha del registro<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{!data.mealPlans.length&&<p>No hay dietas asignadas.</p>}{data.mealPlans.map(plan=><details key={plan.id} className="care-inset care-diet-plan"><summary>{plan.name} · {plan.total_kcal} kcal</summary><div className="care-diet-columns">{(['normal','rest'] as const).map(type=>{const items=data.mealPlanItems.filter(i=>i.meal_plan_id===plan.id&&(i.day_type??'normal')===type);if(!items.length)return null;return <div key={type} className={`care-diet-column care-diet-column-${type}`}><header>{type==='rest'?<Moon size={19} aria-hidden="true"/>:<Sun size={19} aria-hidden="true"/>}<div><h3>{type==='rest'?'Rest Day':'Plan Normal'}</h3><span>{type==='rest'?'Día de descanso':'Día de entrenamiento'}</span></div><small>{new Set(items.map(i=>i.meal_time)).size} comidas</small></header>{[...new Set(items.map(i=>i.meal_time))].map(time=>{const done=data.activity.some(a=>a.kind==='meal'&&a.data.plan_id===plan.id&&a.data.meal_time===time&&a.data.date===date&&a.data.rest===(type==='rest')&&a.data.completed);return <article className="care-inset care-meal" key={time}><h4><Utensils size={14} aria-hidden="true"/>{mealNames[time]??time.replace(/_/g,' ')}</h4>{items.filter(i=>i.meal_time===time).map(i=>{const food=data.foods.find(f=>f.id===i.food_id);return <p key={i.id}>{food?.name??'Alimento'} · {i.quantity} {i.serving_unit}{food?` · ${Math.round(food.kcal*foodRatio(i.quantity,i.serving_unit,food.serving_size))} kcal`:''}</p>;})}<button className={done?'care-meal-completed':''} aria-pressed={!!done} disabled={busy} onClick={()=>void meal(plan.id,time,type==='rest',!done)}>{done&&<Check size={15}/>} {done?'Completada · desmarcar':'Marcar comida completada'}</button></article>;})}</div>;})}</div></details>)}</section>}
 {<div className="care-tab-panel" hidden={tab!=='progress'}><PortalCheckIn key={`${owner}-${clientId}`} owner={owner} clientId={clientId} activity={data.activity} coach={coach} targetId={tab==='progress'?targetCheckIn:undefined} onViewed={markViewed} onSaved={()=>void load()}/>{data.measurements.length>0&&<section className="care-card"><h3>Evaluaciones del coach</h3><div className="care-table-wrap"><table><thead><tr><th>Fecha</th><th>Peso</th><th>Grasa corporal</th></tr></thead><tbody>{data.measurements.map(m=><tr key={m.id}><td>{m.date.slice(0,10)}</td><td>{m.weight} kg</td><td>{m.body_fat!=null?`${m.body_fat}%`:'Sin registrar'}</td></tr>)}</tbody></table></div></section>}</div>}</>}
 </div>;
}
