'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {hasPendingCloudWrites,retryCloudSave,exportCloudBackup} from '@/lib/db';
import {monitoredErrors} from '@/lib/error-monitor';
export function QualityPanel(){
 const [backups,setBackups]=useState<{id:number;revision:number;created_at:string;bytes:number}[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [restore,setRestore]=useState<number|null>(null);const [confirmation,setConfirmation]=useState('');
 async function load(){const {data,error}=await supabase.rpc('dietforge_backup_list');if(error)setMessage('No se pudieron consultar los respaldos.');else setBackups(data??[]);}
 useEffect(()=>{let live=true;void supabase.rpc('dietforge_backup_list').then(({data,error})=>{if(!live)return;if(error)setMessage('No se pudieron consultar los respaldos.');else setBackups(data??[]);});return ()=>{live=false;};},[]);
 async function capture(){setBusy(true);try{await retryCloudSave();if(hasPendingCloudWrites())throw Error('Espera a que termine la sincronización.');const {error}=await supabase.rpc('dietforge_capture_backup');if(error)throw error;await load();setMessage('Respaldo creado.');}catch{setMessage('No se pudo crear el respaldo.');}finally{setBusy(false);}}
 async function download(id:number){setBusy(true);try{const {data,error}=await supabase.rpc('dietforge_backup_get',{b:id});if(error)throw error;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`dietforge-backup-${id}.json`;a.click();URL.revokeObjectURL(url);}catch{setMessage('No se pudo descargar el respaldo.');}finally{setBusy(false);}}
 async function recover(){if(restore===null||confirmation!=='RESTAURAR')return;setBusy(true);try{await retryCloudSave();if(hasPendingCloudWrites())throw Error('Sincronización pendiente.');const current=await supabase.rpc('dietforge_load');if(current.error)throw current.error;const {error}=await supabase.rpc('dietforge_backup_restore',{b:restore,expected:current.data.revision,mutation:crypto.randomUUID()});if(error)throw error;window.location.reload();}catch{setMessage('No se restauró. Puede existir una edición más reciente; actualiza y revisa antes de reintentar.');setBusy(false);}}
 return <div className="care-page"><section className="care-card"><h1>Calidad y recuperación</h1><p>Cada guardado del workspace conserva automáticamente su versión anterior. La restauración comprueba la revisión y conserva registros nuevos del cliente.</p><div className="care-actions"><button disabled={busy} onClick={()=>void capture()}>Crear respaldo ahora</button><button onClick={exportCloudBackup}>Descargar estado local</button><button disabled={busy} onClick={()=>void load()}>Actualizar</button></div>{message&&<p role="status">{message}</p>}<div className="care-table-wrap"><table><thead><tr><th>Fecha</th><th>Revisión</th><th>Tamaño</th><th>Acciones</th></tr></thead><tbody>{backups.map(b=><tr key={b.id}><td>{new Date(b.created_at).toLocaleString()}</td><td>{b.revision}</td><td>{Math.ceil(b.bytes/1024)} KB</td><td><button disabled={busy} onClick={()=>void download(b.id)}>Descargar</button><button disabled={busy} onClick={()=>{setRestore(b.id);setConfirmation('');}}>Restaurar</button></td></tr>)}</tbody></table></div>{restore!==null&&<div className="care-inset"><h2>Restaurar respaldo {restore}</h2><p>Reemplazará la programación del workspace con esta versión. Se conservará una copia de la versión actual. Escribe RESTAURAR para confirmar.</p><input aria-label="Confirmar restauración" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/><button disabled={busy||confirmation!=='RESTAURAR'} onClick={()=>void recover()}>Confirmar restauración</button><button onClick={()=>setRestore(null)}>Cancelar</button></div>}</section><section className="care-card"><h2>Monitoreo de esta sesión</h2><p>{monitoredErrors().length} errores de ejecución detectados. El registro solo conserva categorías y fechas; no captura datos de clientes.</p>{monitoredErrors().map((e,i)=><p key={i}>{e.at} · {e.type}</p>)}</section></div>;
}
