'use client';
import {useState} from 'react';
import type {TrainingProgram} from '@/types';
import {makeSession,sessionErrors,performanceSummary,sessionsFromActivity,type Activity,type TrainingSession} from '@/lib/training-tracking';
import {writeActivity} from '@/lib/client-portal';
import {TrainingVideo} from './TrainingMedia';
import {exerciseVideo} from '@/lib/training-media';
import {trainingDays} from '@/lib/training';
export function SessionTracker({owner,clientId,programs,activity,onSaved}:{owner:string;clientId:number;programs:TrainingProgram[];activity:Activity[];onSaved:()=>void}){
 const [programId,setProgramId]=useState(programs[0]?.id??0);const program=programs.find(p=>p.id===programId)??programs[0];
 const [week,setWeek]=useState(1);const [day,setDay]=useState('');const [session,setSession]=useState<TrainingSession|null>(null);const [recordId,setRecordId]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const sessions=sessionsFromActivity(activity);const records=performanceSummary(sessions);
 const change=(fn:(s:TrainingSession)=>void)=>setSession(s=>{if(!s)return s;const n=structuredClone(s);fn(n);return n;});
 async function save(){if(!session)return;const issues=sessionErrors(session);if(issues.length){setMessage(issues.join(' '));return;}setBusy(true);try{await writeActivity(owner,clientId,{id:recordId,kind:'session',data:session as unknown as Record<string,unknown>});setMessage('Sesión guardada.');onSaved();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="care-card"><h2>Registro de entrenamiento</h2><p>Compara la prescripción con tus series reales. Guarda el avance o completa la sesión.</p>
 {program&&<section className="training-media-section"><h3>Videos del coach</h3><p>Aquí aparecen únicamente los videos que tu coach haya añadido a la rutina.</p>{program.resources?.map(r=><TrainingVideo key={r.id} value={r.url} label={r.title}/>)}{(trainingDays(program,week).find(d=>d.id===day)??trainingDays(program,week)[0])?.exercises.map(e=><TrainingVideo key={e.id} value={exerciseVideo(e)} label={`Técnica · ${e.name}`}/>)}</section>}
 {program?<><p className="care-notice">Tu coach define la rutina. Aquí puedes registrar peso, repeticiones, RIR, series completadas, fatiga y notas; no puedes cambiar la prescripción.</p><div className="care-form"><label>Rutina<select value={program.id} onChange={e=>{setProgramId(Number(e.target.value));setDay('');setWeek(1);}}>{programs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Semana<select value={week} onChange={e=>{setWeek(Number(e.target.value));setDay('');}}>{Array.from({length:program.duration_weeks},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label><label>Día<select value={day||trainingDays(program,week)[0]?.id} onChange={e=>setDay(e.target.value)}>{trainingDays(program,week).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button disabled={busy||!trainingDays(program,week).length} onClick={()=>{if(session&&!window.confirm('¿Abrir otra sesión y descartar los cambios sin guardar?'))return;const selected=day||trainingDays(program,week)[0]?.id;if(!selected)return;setSession(makeSession(program,selected,week));setRecordId(crypto.randomUUID());setMessage('');}}>Iniciar registro</button></div>
 {session&&<div className="care-stack"><div className="care-form"><label>Fecha<input type="date" value={session.date} onChange={e=>change(s=>{s.date=e.target.value;})}/></label><label>Fatiga (1–10)<input type="number" min="1" max="10" value={session.fatigue} onChange={e=>change(s=>{s.fatigue=Number(e.target.value);})}/></label><label>Notas<textarea value={session.notes} onChange={e=>change(s=>{s.notes=e.target.value;})}/></label></div>{session.exercises.map((exercise,ei)=><article key={exercise.exercise_id} className="care-inset"><h3>{exercise.name}</h3><p>Meta: {exercise.target.sets} series · {exercise.target.reps_min}–{exercise.target.reps_max} reps · RIR {exercise.target.rir_start}–{exercise.target.rir_end}{exercise.target.load_kg!=null?` · ${exercise.target.load_kg} kg`:''}</p><div className="care-table-wrap"><table><thead><tr><th>Serie</th><th>kg</th><th>Reps reales</th><th>RIR real</th><th>Hecha</th></tr></thead><tbody>{exercise.sets.map((set,si)=><tr key={si}><td>{si+1}</td>{(['kg','reps','rir'] as const).map(field=><td key={field}><input aria-label={`${exercise.name} serie ${si+1} ${field}`} type="number" min="0" step={field==='kg'?'0.5':'1'} value={set[field]} onChange={e=>change(s=>{s.exercises[ei].sets[si][field]=Number(e.target.value);})}/></td>)}<td><input aria-label={`Completar ${exercise.name} serie ${si+1}`} type="checkbox" checked={set.completed} onChange={e=>change(s=>{s.exercises[ei].sets[si].completed=e.target.checked;})}/></td></tr>)}</tbody></table></div></article>)}<label className="care-check"><input type="checkbox" checked={session.completed} onChange={e=>change(s=>{s.completed=e.target.checked;})}/>Sesión completada</label><button disabled={busy} onClick={()=>void save()}>{busy?'Guardando…':'Guardar registro'}</button></div>}</>:<p>No hay rutinas publicadas.</p>}
 {message&&<p role="status">{message}</p>}
 <h3>Historial de sesiones</h3><div className="care-list">{activity.filter(a=>a.kind==='session').sort((a,b)=>String(b.data.date).localeCompare(String(a.data.date))).map(a=><button key={a.id} disabled={busy} onClick={()=>{if(session&&!window.confirm('¿Abrir el registro guardado y descartar cambios sin guardar?'))return;setRecordId(a.id);setSession(structuredClone(a.data) as unknown as TrainingSession);}}>{String(a.data.date)} · Semana {String(a.data.week)} · {a.data.completed?'Completada':'En curso'}</button>)}</div>
 <h3>Récords e historial por ejercicio</h3><div className="care-table-wrap"><table><thead><tr><th>Ejercicio</th><th>Mayor carga</th><th>Mayor número de reps</th><th>Volumen registrado</th></tr></thead><tbody>{records.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.kg} kg</td><td>{r.reps}</td><td>{Math.round(r.tonnage)} kg × reps</td></tr>)}</tbody></table></div>
 </section>;
}
