'use client';
import {useEffect,useState} from 'react';
import type {TrainingProgram,ExerciseLibraryItem} from '@/types';
import {db,getPreference,setPreference} from '@/lib/db';
import {detailedVolume,duplicateTraining,progressionSuggestion,sessionsFromActivity,type TrainingSession} from '@/lib/training-tracking';
import {createTrainingDraft,exerciseFromLibrary,independentTrainingProgram,trainingDays} from '@/lib/training';
import {readPortal} from '@/lib/client-portal';
import {supabase} from '@/lib/supabase';
import library from '@/data/training-exercises.json';
interface Template {id:string;name:string;program:TrainingProgram}
function getTemplates():Template[]{try{return JSON.parse(getPreference('training_templates')??'[]');}catch{return [];}}
export function TrainingTools({program,week,onChange,onOpen}:{program:TrainingProgram;week:number;onChange:(p:TrainingProgram)=>void;onOpen:(p:TrainingProgram)=>void}){
 const [templates,setTemplates]=useState(getTemplates);const [target,setTarget]=useState(program.client_id);const [message,setMessage]=useState('');const [sessions,setSessions]=useState<TrainingSession[]>([]);const [compare,setCompare]=useState(0);
 useEffect(()=>{let live=true;void supabase.auth.getUser().then(async({data})=>{if(data.user){const dataSet=await readPortal(data.user.id,program.client_id);if(live)setSessions(sessionsFromActivity(dataSet.activity));}}).catch(()=>{if(live)setMessage('No se pudo cargar el historial para progresión.');});return ()=>{live=false;};},[program.client_id]);
 const volume=detailedVolume(program,week);const other=db.getTrainingProgram(compare);const previous=detailedVolume(other??program,other?Math.min(week,other.duration_weeks):Math.max(1,week-1));
 function saveTemplate(){const item={id:crypto.randomUUID(),name:program.name,program:duplicateTraining(program,0)};const next=[...templates,item];setPreference('training_templates',JSON.stringify(next));setTemplates(next);setMessage('Plantilla guardada.');}
 function duplicate(p:TrainingProgram){const copy=duplicateTraining(p,target,`${p.name} · copia`);const saved=db.saveTrainingProgram(copy);setMessage('Rutina duplicada como borrador.');if(target===program.client_id)onOpen(saved);}
 function preset(type:string){const draft={...createTrainingDraft(program.client_id,'Plantilla'),id:0,created_at:'',updated_at:''};const groups=type==='ppl'?[['Pectoral','Deltoides','Tríceps'],['Espalda','Bíceps'],['Cuadriceps','Isquiosurales','Pantorrilla']]:type==='upper'?[['Pectoral','Espalda','Deltoides','Bíceps','Tríceps'],['Cuadriceps','Isquiosurales','Glúteo','Pantorrilla'],['Pectoral','Espalda','Deltoides','Bíceps'],['Cuadriceps','Isquiosurales','Glúteo']]:[['Bíceps','Tríceps','Deltoides'],['Cuadriceps','Isquiosurales'],['Espalda','Pectoral'],['Bíceps','Tríceps']];draft.name=type==='ppl'?'Push / Pull / Legs':type==='upper'?'Upper / Lower':'Especialización de brazos';draft.days=groups.map((group,i)=>({id:crypto.randomUUID(),day_number:i+1,name:type==='ppl'?['Push','Pull','Legs'][i]:`Día ${i+1}`,weekday_offset:type==='upper'?[0,1,3,4][i]:i,exercises:group.map(m=>(library as ExerciseLibraryItem[]).find(e=>e.muscle_group===m)).filter((e):e is ExerciseLibraryItem=>!!e).map(e=>exerciseFromLibrary(e,draft.duration_weeks))}));draft.week_days=undefined;onOpen(independentTrainingProgram(draft));setMessage('Plantilla base cargada. Cada semana ya puede tener días y ejercicios independientes.');}
 return <details className="care-card"><summary>Plantillas, progresión y análisis de volumen</summary><div className="care-stack"><h3>Plantillas reutilizables</h3><div className="care-actions"><button onClick={saveTemplate}>Guardar bloque como plantilla</button><button onClick={()=>preset('ppl')}>Push / Pull / Legs</button><button onClick={()=>preset('upper')}>Upper / Lower</button><button onClick={()=>preset('arms')}>Especialización</button></div><div className="care-form"><label>Cliente destino<select value={target} onChange={e=>setTarget(Number(e.target.value))}>{db.getClients().map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button onClick={()=>duplicate(program)}>Duplicar rutina al cliente</button></div>{templates.map(t=><div key={t.id} className="care-heading"><strong>{t.name}</strong><button onClick={()=>duplicate(t.program)}>Usar plantilla en cliente destino</button></div>)}
 <h3>Volumen directo e indirecto · semana {week}</h3><p>Las series indirectas se ponderan con el factor configurado en cada ejercicio. Los rangos son objetivos editables del coach.</p><label>Comparar con<select value={compare} onChange={e=>setCompare(Number(e.target.value))}><option value={0}>Semana anterior del bloque</option>{db.getTrainingPrograms(program.client_id).filter(p=>p.id!==program.id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="care-table-wrap"><table><thead><tr><th>Músculo</th><th>Directas</th><th>Indirectas</th><th>Frecuencia</th><th>Cambio</th><th>Rango mín.</th><th>máx.</th></tr></thead><tbody>{volume.map(v=>{const range=program.volume_ranges?.[v.muscle];return <tr key={v.muscle}><td>{v.muscle}{range&&(v.total<range.min||v.total>range.max)&&' · revisar'}</td><td>{v.direct}</td><td>{v.indirect}</td><td>{v.frequency}x</td><td>{(v.total-(previous.find(p=>p.muscle===v.muscle)?.total??0)).toFixed(1)}</td>{(['min','max'] as const).map(field=><td key={field}><input aria-label={`${v.muscle} ${field}`} type="number" min="0" max="100" value={range?.[field]??''} onChange={e=>{const next=structuredClone(program);next.volume_ranges??={};next.volume_ranges[v.muscle]={min:range?.min??0,max:range?.max??100,[field]:Math.max(0,Math.min(100,Number(e.target.value)))};onChange(next);}}/></td>)}</tr>;})}</tbody></table></div>
 <h3>Progresión asistida</h3><p>Las propuestas usan registros completos. Aprobar modifica únicamente la semana seleccionada; guarda el bloque para publicar el ajuste.</p>{trainingDays(program,week).flatMap(d=>d.exercises).map(e=>{const suggestion=progressionSuggestion(e,sessions,week);return <div className="care-inset" key={e.id}><strong>{e.name}</strong><p>{suggestion.message}</p>{(suggestion.action==='load'||suggestion.action==='reps')&&<button onClick={()=>{const next=structuredClone(program);const target=trainingDays(next,week).flatMap(d=>d.exercises).find(x=>x.id===e.id)?.prescriptions.find(p=>p.week===week);if(target){if(suggestion.load_kg!=null)target.load_kg=suggestion.load_kg;if(suggestion.reps_min!=null)target.reps_min=suggestion.reps_min;if(suggestion.reps_max!=null)target.reps_max=suggestion.reps_max;next.approval_history??=[];next.approval_history.push({date:new Date().toISOString(),exercise_id:e.id,week,message:suggestion.message});onChange(next);setMessage('Propuesta aprobada en el borrador. Guarda los cambios.');}}}>Aprobar propuesta</button>}</div>;})}
 {program.approval_history?.length? <details><summary>Historial de aprobaciones ({program.approval_history.length})</summary>{program.approval_history.map((h,i)=><p key={i}>{h.date.slice(0,10)} · semana {h.week} · {h.message}</p>)}</details>:null}{message&&<p role="status">{message}</p>}</div></details>;
}
